name: Latest blog posts

on:
  push:
    branches:
      - main

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with: 
          max_post_count: "5"
          feed_list: 'https://testingsresourcehub.blogspot.com/'
          gh_token: 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
          readme_path: ./README.md
          disable_sort: false
#           filter_comments: medium,stackoverflow/Comment by $author/,stackexchange/Comment by $author/
          template: default
          date_format: UTC:ddd mmm dd yyyy h:MM TT
          user_agent: rss-parser
          accept_header: application/rss+xml
          commit_message: Updated with the latest blog posts
          committer_username: blog-post-bot
          committer_email: blog-post-bot@example.com
          output_only: false
          enable_keepalive: true
          retry_count: 0
          retry_wait_time: 1
          disable_html_encoding: false
          categories_template: default
          disable_item_validation: false
          skip_commit: false
